### PR TITLE
change expected type of replace body to String in base64

### PR DESCRIPTION
**Pull request by Hexilee**
Signed-off-by: hexilee <i@hexilee.me>

As we use golang client in Chaos Mesh, and golang encodes bytes in base64 by default, we should change the expected body type.

### CODE REVIEW

**Comment by STRRL** [comment]
How about appending an example in `config-examples`?

**Comment by Hexilee** [comment]
> 
> 
> How about appending an example in `config-examples`?

Example appended.

**Comment by STRRL** [comment]
Still facing the same issue about Content-Length https://github.com/chaos-mesh/chaos-mesh/issues/2152.

Here is my scenario:

The origin response is `{"hello":"world"}`, contains 18 characters.
If I want to replace the body with `hello chaos mesh`(17 chars), `curl` tells me:

```
curl localhost:8080
curl: (52) Empty reply from server
```

with logs in chaos-daemon

```
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aug 02 04:22:46.532 DEBUG hyper::proto::h1::io: parsed 3 headers
Aug 02 04:22:46.533 DEBUG hyper::proto::h1::conn: incoming body is empty
Aug 02 04:22:46.534 DEBUG hyper::client::connect::dns: resolving host="127.0.0.1"
Aug 02 04:22:46.535 DEBUG hyper::proto::h1::io: flushed 78 bytes
Aug 02 04:22:46.536 DEBUG hyper::proto::h1::io: parsed 8 headers
Aug 02 04:22:46.536 DEBUG hyper::proto::h1::conn: incoming body is content-length (18 bytes)
Aug 02 04:22:46.536 DEBUG hyper::proto::h1::conn: incoming body completed
Aug 02 04:22:46.537 DEBUG hyper::client::pool: pooling idle connection for ("http", 127.0.0.1:80)
Aug 02 04:22:46.537 DEBUG tproxy::tproxy: response matched
Aug 02 04:22:46.537 DEBUG apply_response_action{response=Response { status: 200, version: HTTP/1.1, headers: {"server": "nginx/1.21.1", "date": "Mon, 02 Aug 2021 04:22:46 GMT", "content-type": "text/html", "content-length": "18", "last-modified": "Mon, 02 Aug 2021 04:21:55 GMT", "connection": "keep-alive", "etag": "\"610772e3-12\"", "accept-ranges": "bytes"}, body: Body(Streaming) } actions=Actions { abort: false, delay: None, replace: Some(ReplaceAction { path: Some("/"), method: None, body: Some([104, 101, 108, 108, 111, 32, 99, 104, 97, 111, 115, 32, 109, 101, 115, 104, 10]), code: None, queries: None, headers: None }), patch: None }}: tproxy::handler: action applied: Response { status: 200, version: HTTP/1.1, headers: {"server": "nginx/1.21.1", "date": "Mon, 02 Aug 2021 04:22:46 GMT", "content-type": "text/html", "content-length": "18", "last-modified": "Mon, 02 Aug 2021 04:21:55 GMT", "connection": "keep-alive", "etag": "\"610772e3-12\"", "accept-ranges": "bytes"}, body: Body(Full(b"hello chaos mesh\n")) }
thread 'tokio-runtime-worker' panicked at 'payload claims content-length of 17, custom content-length header claims 18', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.14.4/src/proto/h1/role.rs:414:37

```

If I use `hello chaos mesh `(18 chars, appending one whitespace at the last), everything works well:

```
curl localhost:8080
hello chaos mesh 
```

**Comment by STRRL** [comment]
So this PR works well!

**Review by STRRL — APPROVED** [review]

**Comment by STRRL** [comment]
looking forward to bug fixing of chaos-mesh/chaos-mesh#2152, :heart:

**Review by YangKeao — APPROVED** [review]
LGTM

**Pull request merged**
